services:
  navidrome:
    build: 
      context: ./navidrome
      dockerfile: Dockerfile
    container_name: navidrome
    ports:
      - "4533:4533"
    volumes:
      - ./navidrome-data:/data
      - ./music:/music
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_PORT: 4533
    restart: unless-stopped

networks:
  music-network:
    driver: bridge