services:
  navidrome:
    build: 
      context: ./navidrome
      dockerfile: Dockerfile
    container_name: navidrome
    ports:
      - "4533:4533"
    volumes:
      - ./navidrome-data:/data
      - ./music:/music
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_PORT: 4533
    restart: unless-stopped
    networks:
      - navidrome-network

  navidrome-tunnel:
    container_name: navidrome-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - navidrome
    networks:
      - navidrome-network

networks:
  navidrome-network:
    driver: bridge